title: "Sultan Taj"
description: "Welcome to my blog site!"
url: "https://staj-55.github.io"
baseurl: "/blogs"

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Sultan Taj"
