title: "Sultan Taj"
description: "Welcome to my blog site!"
url: "https://STaj55.github.io"
# If you are using a project site (not username.github.io), add:
# baseurl: "/REPO"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto

author:
  name: "Your Name"

header_pages:
  - about.md
